retrunrfm <- read.csv("F://Akarshan's Document//Akarshan//excelrDATASCIENCE//Project1//Data Sets//returnsrfm.csv")
salesrfm <- read.csv("F://Akarshan's Document//Akarshan//excelrDATASCIENCE//Project1//Data Sets//rfm.csv")
#a=merge(retrunrfm,salesrfm)
library(data.table)
setnames(retrunrfm,"Dealer.ID","dealer")
library(dplyr)
full <- full_join(salesrfm,retrunrfm,by=NULL)
colSums(is.na(full))
View(full)
